# Generated by Django 3.2.5 on 2021-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('doing', 'Doing'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='doing', max_length=8),
        ),
    ]
