# Generated by Django 3.2.5 on 2021-07-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_status'),
        ('app', '0004_auto_20210721_2204'),
    ]

    operations = [
    ]
