# Generated by Django 3.2.5 on 2021-07-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0002_order_status_0004_auto_20210721_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
